---
apiVersion: v1
kind: Service
metadata:
  name: rode-red
spec:
  type: NodePort
  selector:             # indicates into which pods ClusterIP provides access
    app: mosquitto
  ports:
    - protocol: TCP
      port: 61883
      targetPort: 1880    # port exposed by Pod
      nodePort: 31880
