apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: node-red
spec:
  selector:
    app: node-red
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80    #Move Node-Red to port 80
    targetPort: 1880
