apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: node-red
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 1880
    targetPort: 1880
  selector:
    app: node-red
  type: LoadBalancer
